theme: minimal-mistakes-jekyll
minimal_mistakes_skin    : "default" # "air", "contrast", "dark", "dirt", "mint", "sunrise"

locale                   : "en"
title                    : "Yuan's blog'"
title_separator          : "-"
name                     : "Yuan Yu Yuan"
description              : "A personal blog"
url                      : "https://yuanyuyuan.gitlab.io"
baseurl                  : "/blog"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
