theme: minimal-mistakes-jekyll
minimal_mistakes_skin    : "default" # "air", "contrast", "dark", "dirt", "mint", "sunrise"

locale                   : "en"
title                    : "Yuan's blog"
title_separator          : "-"
name                     : "Yuan Yu Yuan"
description              : "A personal blog"
url                      : "https://yuanyuyuan.github.io"
baseurl                  : "/blog"
repository               : "blog"
teaser                   : "/assets/images/unsplash-1.jpg"

# Site Author
author:
  name             : "Yuan Yu Yuan"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "Someone who likes Linux, robot and math"
  location         : "Taiwan"
  email            : "az6980522@gmail.com"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "YuanYuYuan"
  gitlab           : "YuanYuYuan"
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : # "john-doe-12345678" (the last part of your profile url, e.g. https://www.linkedin.com/in/john-doe-12345678)
  pinterest        :
  soundcloud       :
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          : "https://www.youtube.com/channel/UCHoFSmS_Gr5Og29pQv4ctwA"

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Reading Files
include:
  - _pages
exclude:
  - vendor
  - .sass-cache
  - Gemfile
  - README
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
